-------------------------------------------------------------------------------------------------
--	Copyright (c) INFINITT Co., Ltd.
--	All Rights Reserved
-------------------------------------------------------------------------------------------------

CREATE OR REPLACE
PACKAGE sp_filter
AS

-------------------------------------------------------------------------------------------------
-- call procedure for ODBC BROKER
-- Use with PBMFilter for G3
-------------------------------------------------------------------------------------------------
	PROCEDURE adt_to_patient
	(
		v_a_broker_aetitle				IN VARCHAR2,
		v_a_event_type					IN VARCHAR2,
		v_a_patient_account_no			IN VARCHAR2,
		v_a_patient_id			 		IN VARCHAR2,
		v_a_patient_name		 		IN VARCHAR2,
		v_a_patient_ename		 		IN VARCHAR2,
		v_a_patient_ssn			 		IN VARCHAR2,
		v_a_patient_birth_dttm			IN VARCHAR2,
		v_a_patient_sex					IN VARCHAR2,
		v_a_patient_ethnic_group		IN VARCHAR2,
		v_a_patient_phone_no			IN VARCHAR2,
		v_a_patient_email				IN VARCHAR2,
		v_a_patient_address		 		IN VARCHAR2,
		v_a_patient_fax_no		 		IN VARCHAR2,
		v_a_patient_zipcode		 		IN VARCHAR2,
		v_a_patient_class		 		IN VARCHAR2,
		v_a_patient_location			IN VARCHAR2,
		v_a_current_doctor_id			IN VARCHAR2,
		v_a_current_doctor_name			IN VARCHAR2,
		v_a_prior_patient_location		IN VARCHAR2,
		v_a_prior_patient_id			IN VARCHAR2,
		v_a_patient_weight		 		IN VARCHAR2,
		v_a_patient_size		 		IN VARCHAR2,
		v_a_patient_blood_type			IN VARCHAR2,
		v_a_patient_pregnancy_status 	IN VARCHAR2,
		v_a_adt_field1					IN VARCHAR2,
		v_a_adt_field2					IN VARCHAR2,
		v_a_adt_field3					IN VARCHAR2,
		v_a_adt_field4					IN VARCHAR2,
		v_a_adt_field5					IN VARCHAR2,
		v_a_adt_field6					IN VARCHAR2,
		v_a_adt_field7					IN VARCHAR2,
		v_a_adt_field8					IN VARCHAR2,
		v_a_adt_field9					IN VARCHAR2,
		v_a_adt_field10					IN VARCHAR2,

		v_p_event_type					OUT VARCHAR2,
		v_p_patient_id					OUT VARCHAR2,
		v_p_prior_patient_id			OUT VARCHAR2,
		v_p_patient_name				OUT VARCHAR2,
		v_p_english_name				OUT VARCHAR2,
		v_p_patient_ssn					OUT VARCHAR2,
		v_p_patient_birth_dttm			OUT VARCHAR2,
		v_p_patient_sex					OUT VARCHAR2,
		v_p_patient_weight				OUT VARCHAR2,
		v_p_patient_size				OUT VARCHAR2,
		v_p_ethnic_group				OUT VARCHAR2,
		v_p_tel_no			 			OUT VARCHAR2,
		v_p_fax_no			 			OUT VARCHAR2,
		v_p_zipcode						OUT VARCHAR2,
		v_p_address						OUT VARCHAR2,
		v_p_email						OUT VARCHAR2,
		v_p_blood_type					OUT VARCHAR2,
		v_p_pregnancy_status			OUT VARCHAR2,
		v_p_current_location			OUT VARCHAR2,
		v_p_current_residency			OUT VARCHAR2,
		v_p_current_department			OUT VARCHAR2,
		v_p_current_doctor_id			OUT VARCHAR2,
		v_p_current_doctor_name			OUT VARCHAR2,
		v_p_admit_dttm			 		OUT VARCHAR2,
		v_p_discharge_dttm		 		OUT VARCHAR2,
		v_p_patient_id_issuer			OUT VARCHAR2,
		v_p_last_name					OUT VARCHAR2,
		v_p_first_name					OUT VARCHAR2,
		v_p_middle_name					OUT VARCHAR2,
		v_p_prefix						OUT VARCHAR2,
		v_p_suffix						OUT VARCHAR2,
		v_p_marital_status				OUT VARCHAR2,
		v_p_confidentiality				OUT VARCHAR2,
		v_p_patient_death_dttm			OUT VARCHAR2,
		v_p_blood_type_rh				OUT VARCHAR2,
		v_p_citizenship					OUT VARCHAR2,
		v_p_occupation					OUT VARCHAR2,
		v_p_race_code					OUT VARCHAR2,
		v_p_language_code				OUT VARCHAR2,
		v_p_religion_code				OUT VARCHAR2,
		v_p_birth_place					OUT VARCHAR2,
		v_p_multiple_birth_status		OUT VARCHAR2,
		v_p_birth_order					OUT VARCHAR2,
		v_p_cell_phone_no				OUT VARCHAR2,
		v_p_pregnancy_code				OUT VARCHAR2,
		v_p_patient_status				OUT VARCHAR2,
		v_p_account_number				OUT VARCHAR2,
		v_p_contact_type				OUT VARCHAR2,
		v_p_business_phone_no			OUT VARCHAR2,
		v_p_city						OUT VARCHAR2,
		v_p_state						OUT VARCHAR2,
		v_p_country						OUT VARCHAR2,
		v_p_visit_number				OUT VARCHAR2,
		v_p_visit_status				OUT VARCHAR2,
		v_p_consult_doctor_id			OUT VARCHAR2,
		v_p_institution_code			OUT VARCHAR2,
		v_p_visit_comments				OUT VARCHAR2,
		v_p_admit_route					OUT VARCHAR2,
		v_p_last_menstrual_dttm			OUT VARCHAR2,
		v_p_code_abbreviation			OUT VARCHAR2,
		v_p_station_code				OUT VARCHAR2,
		v_p_consult_doctor_name			OUT VARCHAR2,
		v_p_broker_aetitle				OUT VARCHAR2,
		v_p_broker_type					OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE orm_to_mwl
	(
		v_o_broker_aetitle				IN VARCHAR2,
		v_o_message_control_id			IN VARCHAR2,
		v_o_event_type					IN VARCHAR2,
		v_o_patient_account_no			IN VARCHAR2,
		v_o_patient_id			 		IN VARCHAR2,
		v_o_patient_name		 		IN VARCHAR2,
		v_o_patient_ename		 		IN VARCHAR2,
		v_o_patient_ssn			 		IN VARCHAR2,
		v_o_patient_birth_dttm			IN VARCHAR2,
		v_o_patient_sex					IN VARCHAR2,
		v_o_refering_doctor_id			IN VARCHAR2,
		v_o_refering_doctor_name		IN VARCHAR2,
		v_o_attending_doctor_id			IN VARCHAR2,
		v_o_attending_doctor_name		IN VARCHAR2,
		v_o_prior_patient_location		IN VARCHAR2,
		v_o_consulting_doctor_id		IN VARCHAR2,
		v_o_consulting_doctor_name		IN VARCHAR2,
		v_o_patient_class				IN VARCHAR2,
		v_o_scheduled_date_time			IN VARCHAR2,
		v_o_filler_order_no				IN VARCHAR2,
		v_o_quantity_timing				IN VARCHAR2,
		v_o_order_control_id			IN VARCHAR2,
		v_o_universal_service_id		IN VARCHAR2,
		v_o_specimen_source				IN VARCHAR2,
		v_o_diagnostic_serv_sect_id		IN VARCHAR2,
		v_o_placer_field1				IN VARCHAR2,
		v_o_placer_field2		 		IN VARCHAR2,
		v_o_filler_field1				IN VARCHAR2,
		v_o_filler_field2				IN VARCHAR2,
		v_o_reason_for_study			IN VARCHAR2,
		v_o_entering_organization		IN VARCHAR2,
		v_o_reference_pointer			IN VARCHAR2,
		v_o_request_dttm		 		IN VARCHAR2,
		v_o_specialty			 		IN VARCHAR2,
		v_o_diagnosis			 		IN VARCHAR2,
		v_o_patient_residency			IN VARCHAR2,
		v_o_orm_field1			 		IN VARCHAR2,
		v_o_orm_field2					IN VARCHAR2,
		v_o_orm_field3					IN VARCHAR2,
		v_o_orm_field4					IN VARCHAR2,
		v_o_orm_field5					IN VARCHAR2,
		v_o_orm_field6					IN VARCHAR2,
		v_o_orm_field7					IN VARCHAR2,
		v_o_orm_field8					IN VARCHAR2,
		v_o_orm_field9					IN VARCHAR2,
		v_o_orm_field10					IN VARCHAR2,
		v_o_zra_field02					IN VARCHAR2,
		v_o_ipc_field01					IN VARCHAR2,
		v_o_ipc_field02					IN VARCHAR2,
		v_o_ipc_field03					IN VARCHAR2,
		v_o_ipc_field04					IN VARCHAR2,
		v_o_ipc_field05					IN VARCHAR2,
		v_o_ipc_field06					IN VARCHAR2,
		v_o_ipc_field07					IN VARCHAR2,
		v_o_ipc_field08					IN VARCHAR2,
		v_o_ipc_field09					IN VARCHAR2,

		v_m_order_control_id			OUT VARCHAR2,
		v_m_event_type					OUT VARCHAR2,
		v_m_character_set				OUT VARCHAR2,
		v_m_scheduled_aetitle			OUT VARCHAR2,
		v_m_scheduled_dttm				OUT VARCHAR2,
		v_m_scheduled_modality			OUT VARCHAR2,
		v_m_scheduled_station			OUT VARCHAR2,
		v_m_scheduled_location			OUT VARCHAR2,
		v_m_scheduled_proc_id			OUT VARCHAR2,
		v_m_scheduled_proc_desc			OUT VARCHAR2,
		v_m_scheduled_action_codes		OUT VARCHAR2,
		v_m_scheduled_proc_status		OUT VARCHAR2,
		v_m_premedication				OUT VARCHAR2,
		v_m_contrast_agent				OUT VARCHAR2,
		v_m_requested_proc_id			OUT VARCHAR2,
		v_m_requested_proc_desc			OUT VARCHAR2,
		v_m_requested_proc_codes		OUT VARCHAR2,
		v_m_requested_proc_priority		OUT VARCHAR2,
		v_m_requested_proc_reason		OUT VARCHAR2,
		v_m_requested_proc_comments		OUT VARCHAR2,
		v_m_study_instance_uid			OUT VARCHAR2,
		v_m_proc_placer_order_no		OUT VARCHAR2,
		v_m_proc_filler_order_no		OUT VARCHAR2,
		v_m_accession_no				OUT VARCHAR2,
		v_m_attend_doctor				OUT VARCHAR2,
		v_m_perform_doctor				OUT VARCHAR2,
		v_m_consult_doctor				OUT VARCHAR2,
		v_m_request_doctor				OUT VARCHAR2,
		v_m_refer_doctor				OUT VARCHAR2,
		v_m_request_department			OUT VARCHAR2,
		v_m_imaging_request_reason		OUT VARCHAR2,
		v_m_imaging_request_comments	OUT VARCHAR2,
		v_m_imaging_request_dttm		OUT VARCHAR2,
		v_m_isr_placer_order_no			OUT VARCHAR2,
		v_m_isr_filler_order_no			OUT VARCHAR2,
		v_m_admission_id				OUT VARCHAR2,
		v_m_patient_transport			OUT VARCHAR2,
		v_m_patient_location			OUT VARCHAR2,
		v_m_patient_residency			OUT VARCHAR2,
		v_m_patient_name				OUT VARCHAR2,
		v_m_patient_id					OUT VARCHAR2,
		v_m_other_patient_name			OUT VARCHAR2,
		v_m_other_patient_id			OUT VARCHAR2,
		v_m_patient_birth_dttm			OUT VARCHAR2,
		v_m_patient_sex					OUT VARCHAR2,
		v_m_patient_weight				OUT VARCHAR2,
		v_m_patient_size				OUT VARCHAR2,
		v_m_patient_state				OUT VARCHAR2,
		v_m_confidentiality				OUT VARCHAR2,
		v_m_pregnancy_status			OUT VARCHAR2,
		v_m_medical_alerts				OUT VARCHAR2,
		v_m_contrast_allergies			OUT VARCHAR2,
		v_m_special_needs				OUT VARCHAR2,
		v_m_specialty					OUT VARCHAR2,
		v_m_diagnosis					OUT VARCHAR2,
		v_m_admit_dttm					OUT VARCHAR2,
		v_m_register_dttm				OUT VARCHAR2,
		v_m_patient_id_issuer			OUT VARCHAR2,
		v_m_last_name					OUT VARCHAR2,
		v_m_first_name					OUT VARCHAR2,
		v_m_middle_name					OUT VARCHAR2,
		v_m_prefix						OUT VARCHAR2,
		v_m_suffix						OUT VARCHAR2,
		v_m_race_code					OUT VARCHAR2,
		v_m_account_no					OUT VARCHAR2,
		v_m_address						OUT VARCHAR2,
		v_m_order_entry_user_id			OUT VARCHAR2,
		v_m_order_entry_location		OUT VARCHAR2,
		v_m_order_callback_phone_no		OUT VARCHAR2,
		v_m_req_proc_status				OUT VARCHAR2,
		v_m_req_proc_code_scheme		OUT VARCHAR2,
		v_m_req_proc_code_version		OUT VARCHAR2,
		v_m_req_proc_code_meaning		OUT VARCHAR2,
		v_m_req_proc_location			OUT VARCHAR2,
		v_m_patient_arrange				OUT VARCHAR2,
		v_m_source_aetitle				OUT VARCHAR2,
		v_m_broker_aetitle				OUT VARCHAR2,
		v_m_broker_type					OUT VARCHAR2,
		v_m_study_ssn					OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE oru_to_report
	(
		v_oru_broker_aetitle			IN VARCHAR2,
		v_oru_message_control_id		IN VARCHAR2,
		v_oru_event_type				IN VARCHAR2,
		v_oru_patient_account_no		IN VARCHAR2,
		v_oru_patient_id				IN VARCHAR2,
		v_oru_patient_name				IN VARCHAR2,
		v_oru_patient_ename				IN VARCHAR2,
		v_oru_patient_ssn				IN VARCHAR2,
		v_oru_patient_birth_dttm		IN VARCHAR2,
		v_oru_patient_sex				IN VARCHAR2,
		v_oru_refering_doctor_id		IN VARCHAR2,
		v_oru_refering_doctor_name		IN VARCHAR2,
		v_oru_attending_doctor_id		IN VARCHAR2,
		v_oru_attending_doctor_name		IN VARCHAR2,
		v_oru_prior_patient_location 	IN VARCHAR2,
		v_oru_consulting_doctor_id		IN VARCHAR2,
		v_oru_consulting_doctor_name	IN VARCHAR2,
		v_oru_patient_class				IN VARCHAR2,
		v_oru_scheduled_date_time		IN VARCHAR2,
		v_oru_filler_order_no			IN VARCHAR2,
		v_oru_quantity_timing			IN VARCHAR2,
		v_oru_universal_service_id		IN VARCHAR2,
		v_oru_requested_date_time		IN VARCHAR2,
		v_oru_specimen_source			IN VARCHAR2,
		v_oru_diagnostic_serv_sect_id	IN VARCHAR2,
		v_oru_placer_field1				IN VARCHAR2,
		v_oru_placer_field2				IN VARCHAR2,
		v_oru_filler_field1				IN VARCHAR2,
		v_oru_filler_field2				IN VARCHAR2,
		v_oru_reason_for_study			IN VARCHAR2,
		v_oru_observation_identifier	IN VARCHAR2,
		v_oru_observation_value			IN VARCHAR2,
		v_oru_observation_status		IN VARCHAR2,
		v_oru_observation_date_time		IN VARCHAR2,
		v_oru_responsible_observer		IN VARCHAR2,
		v_oru_field1					IN VARCHAR2,
		v_oru_field2					IN VARCHAR2,
		v_oru_field3					IN VARCHAR2,
		v_oru_field4					IN VARCHAR2,
		v_oru_field5					IN VARCHAR2,
		v_oru_field6					IN VARCHAR2,
		v_oru_field7					IN VARCHAR2,
		v_oru_field8					IN VARCHAR2,
		v_oru_field9					IN VARCHAR2,
		v_oru_field10					IN VARCHAR2,

		v_r_patient_id					OUT	VARCHAR2,
		v_r_exam_id						OUT	VARCHAR2,
		v_r_report_stat					OUT	VARCHAR2,
		v_r_creator_id					OUT	VARCHAR2,
		v_r_creator_name				OUT	VARCHAR2,
		v_r_create_dttm					OUT	VARCHAR2,
		v_r_dictator_id					OUT	VARCHAR2,
		v_r_dictator_name				OUT	VARCHAR2,
		v_r_dictate_dttm				OUT	VARCHAR2,
		v_r_transcriber_id				OUT	VARCHAR2,
		v_r_transcriber_name			OUT	VARCHAR2,
		v_r_transcribe_dttm				OUT	VARCHAR2,
		v_r_approver_id					OUT	VARCHAR2,
		v_r_approver_name				OUT	VARCHAR2,
		v_r_approve_dttm				OUT	VARCHAR2,
		v_r_reviser_id					OUT	VARCHAR2,
		v_r_reviser_name				OUT	VARCHAR2,
		v_r_revise_dttm					OUT	VARCHAR2,
		v_r_report_type					OUT	VARCHAR2,
		v_r_report_text					OUT	LONG,
		v_r_conclusion					OUT	LONG,
		v_r_event_type					OUT	VARCHAR2,
		v_r_report_control_id			OUT	VARCHAR2,
		v_r_broker_type					OUT	VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE patient_to_patient
	(
		v_broker_aetitle				IN OUT VARCHAR2,
		v_event_type					IN OUT VARCHAR2,
		v_patient_id					IN OUT VARCHAR2,
		v_patient_name					IN OUT VARCHAR2,
		v_english_name		 			IN OUT VARCHAR2,
		v_patient_ssn					IN OUT VARCHAR2,
		v_patient_birth_dttm			IN OUT VARCHAR2,
		v_patient_sex					IN OUT VARCHAR2,
		v_patient_weight	 			IN OUT VARCHAR2,
		v_patient_size		 			IN OUT VARCHAR2,
		v_ethnic_group		 			IN OUT VARCHAR2,
		v_tel_no						IN OUT VARCHAR2,
		v_fax_no		 				IN OUT VARCHAR2,
		v_zipcode		 				IN OUT VARCHAR2,
		v_address		 				IN OUT VARCHAR2,
		v_email							IN OUT VARCHAR2,
		v_blood_type					IN OUT VARCHAR2,
		v_pregnancy_status	 			IN OUT VARCHAR2,
		v_current_location				IN OUT VARCHAR2,
		v_current_residency		 		IN OUT VARCHAR2,
		v_current_department			IN OUT VARCHAR2,
		v_current_doctor_id		 		IN OUT VARCHAR2,
		v_current_doctor_name			IN OUT VARCHAR2,
		v_admit_dttm					IN OUT VARCHAR2,
		v_discharge_dttm				IN OUT VARCHAR2,

		v_p_prior_patient_id			OUT VARCHAR2,
		v_p_patient_id_issuer			OUT VARCHAR2,
		v_p_last_name					OUT VARCHAR2,
		v_p_first_name					OUT VARCHAR2,
		v_p_middle_name					OUT VARCHAR2,
		v_p_prefix						OUT VARCHAR2,
		v_p_suffix						OUT VARCHAR2,
		v_p_marital_status				OUT VARCHAR2,
		v_p_confidentiality				OUT VARCHAR2,
		v_p_patient_death_dttm			OUT VARCHAR2,
		v_p_blood_type_rh				OUT VARCHAR2,
		v_p_citizenship					OUT VARCHAR2,
		v_p_occupation					OUT VARCHAR2,
		v_p_race_code					OUT VARCHAR2,
		v_p_language_code				OUT VARCHAR2,
		v_p_religion_code				OUT VARCHAR2,
		v_p_birth_place					OUT VARCHAR2,
		v_p_multiple_birth_status		OUT VARCHAR2,
		v_p_birth_order					OUT VARCHAR2,
		v_p_cell_phone_no				OUT VARCHAR2,
		v_p_pregnancy_code				OUT VARCHAR2,
		v_p_patient_status				OUT VARCHAR2,
		v_p_account_number				OUT VARCHAR2,
		v_p_contact_type				OUT VARCHAR2,
		v_p_business_phone_no			OUT VARCHAR2,
		v_p_city						OUT VARCHAR2,
		v_p_state						OUT VARCHAR2,
		v_p_country						OUT VARCHAR2,
		v_p_visit_number				OUT VARCHAR2,
		v_p_visit_status				OUT VARCHAR2,
		v_p_consult_doctor_id			OUT VARCHAR2,
		v_p_institution_code			OUT VARCHAR2,
		v_p_visit_comments				OUT VARCHAR2,
		v_p_admit_route					OUT VARCHAR2,
		v_p_last_menstrual_dttm			OUT VARCHAR2,
		v_p_code_abbreviation			OUT VARCHAR2,
		v_p_station_code				OUT VARCHAR2,
		v_p_consult_doctor_name			OUT VARCHAR2,
		v_p_broker_type					OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE mwl_to_mwl
	(
		v_broker_aetitle				IN OUT VARCHAR2,
		v_order_control_id				IN OUT VARCHAR2,
		v_event_type					IN OUT VARCHAR2,
		v_character_set			 		IN OUT VARCHAR2,
		v_scheduled_aetitle				IN OUT VARCHAR2,
		v_scheduled_dttm				IN OUT VARCHAR2,
		v_scheduled_modality			IN OUT VARCHAR2,
		v_scheduled_station				IN OUT VARCHAR2,
		v_scheduled_location			IN OUT VARCHAR2,
		v_scheduled_proc_id				IN OUT VARCHAR2,	-- 10
		v_scheduled_proc_desc			IN OUT VARCHAR2,
		v_scheduled_action_codes		IN OUT VARCHAR2,
		v_scheduled_proc_status			IN OUT VARCHAR2,
		v_premedication					IN OUT VARCHAR2,
		v_contrast_agent				IN OUT VARCHAR2,
		v_requested_proc_id				IN OUT VARCHAR2,
		v_requested_proc_desc			IN OUT VARCHAR2,
		v_requested_proc_codes			IN OUT VARCHAR2,
		v_requested_proc_priority		IN OUT VARCHAR2,
		v_requested_proc_reason			IN OUT VARCHAR2,	-- 20
		v_requested_proc_comments		IN OUT VARCHAR2,
		v_study_instance_uid			IN OUT VARCHAR2,
		v_proc_placer_order_no			IN OUT VARCHAR2,
		v_proc_filler_order_no			IN OUT VARCHAR2,
		v_accession_no					IN OUT VARCHAR2,
		v_attend_doctor					IN OUT VARCHAR2,
		v_perform_doctor				IN OUT VARCHAR2,
		v_consult_doctor				IN OUT VARCHAR2,
		v_request_doctor				IN OUT VARCHAR2,
		v_refer_doctor					IN OUT VARCHAR2,	-- 30
		v_request_department			IN OUT VARCHAR2,
		v_imaging_request_reason		IN OUT VARCHAR2,
		v_imaging_request_comments		IN OUT VARCHAR2,
		v_imaging_request_dttm			IN OUT VARCHAR2,
		v_isr_placer_order_no			IN OUT VARCHAR2,
		v_isr_filler_order_no			IN OUT VARCHAR2,
		v_admission_id					IN OUT VARCHAR2,
		v_patient_transport				IN OUT VARCHAR2,
		v_patient_location				IN OUT VARCHAR2,
		v_patient_residency				IN OUT VARCHAR2,	-- 40
		v_patient_name					IN OUT VARCHAR2,
		v_patient_id					IN OUT VARCHAR2,
		v_other_patient_name			IN OUT VARCHAR2,
		v_other_patient_id				IN OUT VARCHAR2,
		v_patient_birth_dttm			IN OUT VARCHAR2,
		v_patient_sex					IN OUT VARCHAR2,
		v_patient_weight				IN OUT VARCHAR2,
		v_patient_size					IN OUT VARCHAR2,
		v_patient_state					IN OUT VARCHAR2,
		v_confidentiality				IN OUT VARCHAR2,	-- 50
		v_pregnancy_status				IN OUT VARCHAR2,
		v_medical_alerts				IN OUT VARCHAR2,
		v_contrast_allergies			IN OUT VARCHAR2,
		v_special_needs					IN OUT VARCHAR2,
		v_specialty						IN OUT VARCHAR2,
		v_diagnosis						IN OUT VARCHAR2,
		v_admit_dttm					IN OUT VARCHAR2,
		v_register_dttm					IN OUT VARCHAR2,
		v_study_ssn						IN OUT VARCHAR2,
		v_insurance_code				IN OUT VARCHAR2,
		v_emergency						IN OUT VARCHAR2,
		v_special_doctor				IN OUT VARCHAR2,	--62

		v_m_patient_id_issuer			OUT VARCHAR2,
		v_m_last_name					OUT VARCHAR2,
		v_m_first_name					OUT VARCHAR2,
		v_m_middle_name					OUT VARCHAR2,
		v_m_prefix						OUT VARCHAR2,
		v_m_suffix						OUT VARCHAR2,
		v_m_race_code					OUT VARCHAR2,
		v_m_account_no					OUT VARCHAR2,
		v_m_address						OUT VARCHAR2,
		v_m_order_entry_user_id			OUT VARCHAR2,
		v_m_order_entry_location		OUT VARCHAR2,
		v_m_order_callback_phone_no		OUT VARCHAR2,
		v_m_req_proc_status				OUT VARCHAR2,
		v_m_req_proc_code_scheme		OUT VARCHAR2,
		v_m_req_proc_code_version		OUT VARCHAR2,
		v_m_req_proc_code_meaning		OUT VARCHAR2,
		v_m_req_proc_location			OUT VARCHAR2,
		v_m_patient_arrange				OUT VARCHAR2,
		v_m_source_aetitle				OUT VARCHAR2,
		v_m_broker_type					OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE report_to_report
	(
		v_broker_aetitle				IN OUT VARCHAR2,
		v_flow_type		 				IN OUT NUMBER,
		v_patient_id		 			IN OUT VARCHAR2,
		v_exam_id						IN OUT VARCHAR2,
		v_study_instance_uid 			IN OUT VARCHAR2,
		v_report_stat					IN OUT VARCHAR2,
		v_creator_id					IN OUT VARCHAR2,
		v_creator_name					IN OUT VARCHAR2,
		v_create_dttm		 			IN OUT VARCHAR2,
		v_dictator_id					IN OUT VARCHAR2,		--10
		v_dictator_name					IN OUT VARCHAR2,
		v_dictate_dttm		 			IN OUT VARCHAR2,
		v_transcriber_id				IN OUT VARCHAR2,
		v_transcriber_name				IN OUT VARCHAR2,
		v_transcribe_dttm				IN OUT VARCHAR2,
		v_approver_id					IN OUT VARCHAR2,
		v_approver_name					IN OUT VARCHAR2,
		v_approve_dttm					IN OUT VARCHAR2,
		v_reviser_id		 			IN OUT VARCHAR2,
		v_reviser_name					IN OUT VARCHAR2,		--20
		v_revise_dttm		 			IN OUT VARCHAR2,
		v_report_type					IN OUT VARCHAR2,
		v_report_text					IN OUT LONG,
		v_conclusion		 			IN OUT LONG,
		v_study_dttm					IN OUT VARCHAR2,
		v_scheduled_location 			IN OUT VARCHAR2,
		v_perform_department 			IN OUT VARCHAR2,
		v_perform_modality				IN OUT VARCHAR2,
		v_request_dttm					IN OUT VARCHAR2,
		v_request_name					IN OUT VARCHAR2,		--30
		v_request_code					IN OUT VARCHAR2,
		v_request_doctor 				IN OUT VARCHAR2,
		v_perform_doctor				IN OUT VARCHAR2,
		v_refer_doctor					IN OUT VARCHAR2,
		v_scheduled_dttm				IN OUT VARCHAR2,
		v_patient_name		 			IN OUT VARCHAR2,
		v_patient_sex					IN OUT VARCHAR2,
		v_patient_birth_dttm			IN OUT VARCHAR2,
		v_admission_id		 			IN OUT VARCHAR2,
		v_study_comments				IN OUT VARCHAR2,		--40
		v_study_reason					IN OUT VARCHAR2,
		v_attend_doctor					IN OUT VARCHAR2,
		v_patient_location				IN OUT VARCHAR2,
		v_scheduled_station				IN OUT VARCHAR2,  		
		v_r_strFxCode					IN OUT VARCHAR2,
		v_r_strFxDesc		 			IN OUT VARCHAR2,
		v_r_strDxCode					IN OUT VARCHAR2,
		v_r_strDxDesc					IN OUT VARCHAR2,    		
		v_digital_sign_flag   			IN OUT VARCHAR2,   --report digital sign
		v_digital_sign_data             IN OUT VARCHAR2,
		v_digital_sign_dttm             IN OUT VARCHAR2,
		v_certificate_dn                IN OUT VARCHAR2,
		v_digital_sign_key				IN OUT VARCHAR2, 

		v_r_event_type					OUT	VARCHAR2,
		v_r_report_control_id			OUT	VARCHAR2,			--50
		v_r_broker_type					OUT	VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE report_to_oru
	(
		v_r_broker_aetitle				IN VARCHAR2,
		v_r_patient_id		 			IN VARCHAR2,
		v_r_exam_id			 			IN VARCHAR2,
		v_r_study_instance_uid			IN VARCHAR2,
		v_r_report_stat			 		IN VARCHAR2,
		v_r_creator_id					IN VARCHAR2,
		v_r_creator_name				IN VARCHAR2,
		v_r_create_dttm					IN VARCHAR2,
		v_r_dictator_id					IN VARCHAR2,
		v_r_dictator_name				IN VARCHAR2,
		v_r_dictate_dttm				IN VARCHAR2,
		v_r_transcriber_id				IN VARCHAR2,
		v_r_transcriber_name			IN VARCHAR2,
		v_r_transcribe_dttm				IN VARCHAR2,
		v_r_approver_id					IN VARCHAR2,
		v_r_approver_name				IN VARCHAR2,
		v_r_approve_dttm				IN VARCHAR2,
		v_r_reviser_id					IN VARCHAR2,
		v_r_reviser_name				IN VARCHAR2,
		v_r_revise_dttm					IN VARCHAR2,
		v_r_report_type					IN VARCHAR2,
		v_r_report_text					IN LONG,
		v_r_conclusion					IN LONG,
		v_r_study_dttm					IN VARCHAR2,
		v_r_scheduled_location			IN VARCHAR2,
		v_r_perform_department			IN VARCHAR2,
		v_r_perform_modality			IN VARCHAR2,
		v_r_request_dttm				IN VARCHAR2,
		v_r_request_name				IN VARCHAR2,
		v_r_request_code				IN VARCHAR2,
		v_r_request_doctor				IN VARCHAR2,
		v_r_perform_doctor				IN VARCHAR2,
		v_r_refer_doctor				IN VARCHAR2,
		v_r_scheduled_dttm				IN VARCHAR2,
		v_r_patient_name				IN VARCHAR2,
		v_r_patient_sex					IN VARCHAR2,
		v_r_patient_birth_dttm			IN VARCHAR2,
		v_r_admission_id				IN VARCHAR2,
		v_r_study_comments				IN VARCHAR2,
		v_r_study_reason				IN VARCHAR2,
		v_r_attend_doctor				IN VARCHAR2,
		v_r_patient_location			IN VARCHAR2,
		v_r_ScheduledStation			IN VARCHAR2,
		v_r_strFxCode					IN VARCHAR2,
		v_r_strFxDesc					IN VARCHAR2,
		v_r_strDxCode					IN VARCHAR2,
		v_r_strDxDesc					IN VARCHAR2,

		v_oru_message_control_id		OUT VARCHAR2,
		v_oru_event_type				OUT VARCHAR2,
		v_oru_patient_account_no		OUT VARCHAR2,
		v_oru_patient_id		 		OUT VARCHAR2,
		v_oru_patient_name				OUT VARCHAR2,
		v_oru_patient_ename				OUT VARCHAR2,
		v_oru_patient_ssn				OUT VARCHAR2,
		v_oru_patient_birth_dttm		OUT VARCHAR2,
		v_oru_patient_sex				OUT VARCHAR2,
		v_oru_refering_doctor_id		OUT VARCHAR2,
		v_oru_refering_doctor_name		OUT VARCHAR2,
		v_oru_attending_doctor_id		OUT VARCHAR2,
		v_oru_attending_doctor_name		OUT VARCHAR2,
		v_oru_prior_patient_location	OUT VARCHAR2,
		v_oru_consulting_doctor_id		OUT VARCHAR2,
		v_oru_consulting_doctor_name	OUT VARCHAR2,
		v_oru_patient_class				OUT VARCHAR2,
		v_oru_scheduled_date_time		OUT VARCHAR2,
		v_oru_filler_order_no			OUT VARCHAR2,
		v_oru_quantity_timing			OUT VARCHAR2,
		v_oru_universal_service_id		OUT VARCHAR2,
		v_oru_requested_date_time		OUT VARCHAR2,
		v_oru_specimen_source			OUT VARCHAR2,
		v_oru_diagnostic_serv_sect_id	OUT VARCHAR2,
		v_oru_placer_field1				OUT VARCHAR2,
		v_oru_placer_field2				OUT VARCHAR2,
		v_oru_filler_field1	 			OUT VARCHAR2,
		v_oru_filler_field2				OUT VARCHAR2,
		v_oru_reason_for_study			OUT VARCHAR2,
		v_oru_observation_identifier 	OUT VARCHAR2,
		v_oru_observation_value			OUT VARCHAR2,
		v_oru_observation_status		OUT VARCHAR2,
		v_oru_observation_date_time		OUT VARCHAR2,
		v_oru_responsible_observer		OUT VARCHAR2,
		v_oru_field1		 			OUT VARCHAR2,
		v_oru_field2					OUT VARCHAR2,
		v_oru_field3					OUT VARCHAR2,
		v_oru_field4					OUT VARCHAR2,
		v_oru_field5					OUT VARCHAR2,
		v_oru_field6					OUT VARCHAR2,
		v_oru_field7					OUT VARCHAR2,
		v_oru_field8					OUT VARCHAR2,
		v_oru_field9					OUT VARCHAR2,
		v_oru_field10					OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE user_to_user
	(
		v_broker_aetitle				IN OUT	VARCHAR2,
		v_user_id						IN OUT	VARCHAR2,
		v_user_name						IN OUT	VARCHAR2,
		v_password						IN OUT	VARCHAR2,
		v_user_level					IN OUT	VARCHAR2,
		v_user_status					IN OUT	VARCHAR2,
		v_comments						IN OUT	VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE sr_to_report
	(
		v_sr_broker_aetitle				IN	VARCHAR2,
		v_sr_is_complete				IN	NUMBER,
		v_sr_is_verified				IN	NUMBER,
		v_sr_patient_id		 			IN	VARCHAR2,
		v_sr_patient_name	 			IN	VARCHAR2,
		v_sr_patient_sex				IN	VARCHAR2,
		v_sr_patient_birth_date			IN	VARCHAR2,
		v_sr_patient_birth_time	 		IN	VARCHAR2,
		v_sr_study_instance_uid	 		IN	VARCHAR2,
		v_sr_study_id					IN	VARCHAR2,
		v_sr_access_no					IN	VARCHAR2,
		v_sr_study_date					IN	VARCHAR2,
		v_sr_study_time					IN	VARCHAR2,
		v_sr_study_desc					IN	VARCHAR2,
		v_sr_institution				IN	VARCHAR2,
		v_sr_department					IN	VARCHAR2,
		v_sr_consumer_id				IN	VARCHAR2,
		v_sr_consumer_name				IN	VARCHAR2,
		v_sr_creator_id					IN	VARCHAR2,
		v_sr_creator_name				IN	VARCHAR2,
		v_sr_approver_id				IN	VARCHAR2,
		v_sr_approver_name				IN	VARCHAR2,
		v_sr_approve_dttm				IN	VARCHAR2,
		v_sr_report_text				IN	LONG,
		v_sr_report_buffer	 			IN	LONG,
		v_sr_conclusion		 			IN	LONG,

		v_patient_id					OUT	VARCHAR2,
		v_exam_id						OUT	VARCHAR2,
		v_report_stat					OUT	VARCHAR2,
		v_creator_id					OUT	VARCHAR2,
		v_creator_name					OUT	VARCHAR2,
		v_create_dttm					OUT	VARCHAR2,
		v_dictator_id					OUT	VARCHAR2,
		v_dictator_name					OUT	VARCHAR2,
		v_dictate_dttm					OUT	VARCHAR2,
		v_transcriber_id				OUT	VARCHAR2,
		v_transcriber_name				OUT	VARCHAR2,
		v_transcribe_dttm				OUT	VARCHAR2,
		v_approver_id					OUT	VARCHAR2,
		v_approver_name					OUT	VARCHAR2,
		v_approve_dttm					OUT	VARCHAR2,
		v_reviser_id					OUT	VARCHAR2,
		v_reviser_name					OUT	VARCHAR2,
		v_revise_dttm					OUT	VARCHAR2,
		v_report_type					OUT	VARCHAR2,
		v_report_text					OUT	LONG,
		v_conclusion					OUT	LONG,
		v_r_event_type					OUT	VARCHAR2,
		v_r_report_control_id			OUT	VARCHAR2,
		v_r_broker_type					OUT	VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE text_to_mwl
	(
		v_broker_aetitle				IN VARCHAR2,
		v_value01						IN VARCHAR2, 
		v_value02						IN VARCHAR2, 
		v_value03						IN VARCHAR2, 
		v_value04						IN VARCHAR2, 
		v_value05						IN VARCHAR2, 
		v_value06						IN VARCHAR2, 
		v_value07						IN VARCHAR2, 
		v_value08						IN VARCHAR2, 
		v_value09						IN VARCHAR2, 
		v_value10						IN VARCHAR2, 
		v_value11						IN VARCHAR2, 
		v_value12						IN VARCHAR2, 
		v_value13						IN VARCHAR2, 
		v_value14						IN VARCHAR2, 
		v_value15						IN VARCHAR2, 
		v_value16						IN VARCHAR2, 
		v_value17						IN VARCHAR2, 
		v_value18						IN VARCHAR2, 
		v_value19						IN VARCHAR2, 
		v_value20						IN VARCHAR2, 
		v_value21						IN VARCHAR2, 
		v_value22						IN VARCHAR2, 
		v_value23						IN VARCHAR2, 
		v_value24						IN VARCHAR2, 
		v_value25						IN VARCHAR2, 
		v_value26						IN VARCHAR2, 
		v_value27						IN VARCHAR2, 
		v_value28						IN VARCHAR2, 
		v_value29						IN VARCHAR2, 
		v_value30						IN VARCHAR2, 
		v_value31						IN VARCHAR2, 
		v_value32						IN VARCHAR2, 
		v_value33						IN VARCHAR2, 
		v_value34						IN VARCHAR2, 
		v_value35						IN VARCHAR2, 
		v_value36						IN VARCHAR2, 
		v_value37						IN VARCHAR2, 
		v_value38						IN VARCHAR2, 
		v_value39						IN VARCHAR2, 
		v_value40						IN VARCHAR2, 

		v_order_control_id				OUT VARCHAR2,
		v_event_type					OUT VARCHAR2,
		v_character_set					OUT VARCHAR2,
		v_scheduled_aetitle				OUT VARCHAR2,
		v_scheduled_dttm				OUT VARCHAR2,
		v_scheduled_modality			OUT VARCHAR2,
		v_scheduled_station				OUT VARCHAR2,
		v_scheduled_location			OUT VARCHAR2,
		v_scheduled_proc_id				OUT VARCHAR2,
		v_scheduled_proc_desc			OUT VARCHAR2,
		v_scheduled_action_codes		OUT VARCHAR2,
		v_scheduled_proc_status			OUT VARCHAR2,
		v_premedication					OUT VARCHAR2,
		v_contrast_agent				OUT VARCHAR2,
		v_requested_proc_id				OUT VARCHAR2,
		v_requested_proc_desc			OUT VARCHAR2,
		v_requested_proc_codes			OUT VARCHAR2,
		v_requested_proc_priority		OUT VARCHAR2,
		v_requested_proc_reason			OUT VARCHAR2,
		v_requested_proc_comments		OUT VARCHAR2,
		v_study_instance_uid			OUT VARCHAR2,
		v_proc_placer_order_no			OUT VARCHAR2,
		v_proc_filler_order_no			OUT VARCHAR2,
		v_accession_no					OUT VARCHAR2,
		v_attend_doctor					OUT VARCHAR2,
		v_perform_doctor				OUT VARCHAR2,
		v_consult_doctor				OUT VARCHAR2,
		v_request_doctor				OUT VARCHAR2,
		v_refer_doctor					OUT VARCHAR2,
		v_request_department			OUT VARCHAR2,
		v_imaging_request_reason		OUT VARCHAR2,
		v_imaging_request_comments		OUT VARCHAR2,
		v_imaging_request_dttm			OUT VARCHAR2,
		v_isr_placer_order_no			OUT VARCHAR2,
		v_isr_filler_order_no			OUT VARCHAR2,
		v_admission_id					OUT VARCHAR2,
		v_patient_transport				OUT VARCHAR2,
		v_patient_location				OUT VARCHAR2,
		v_patient_residency				OUT VARCHAR2,
		v_patient_name					OUT VARCHAR2,
		v_patient_id					OUT VARCHAR2,
		v_other_patient_name			OUT VARCHAR2,
		v_other_patient_id				OUT VARCHAR2,
		v_patient_birth_dttm			OUT VARCHAR2,
		v_patient_sex					OUT VARCHAR2,
		v_patient_weight				OUT VARCHAR2,
		v_patient_size					OUT VARCHAR2,
		v_patient_state					OUT VARCHAR2,
		v_confidentiality				OUT VARCHAR2,
		v_pregnancy_status				OUT VARCHAR2,
		v_medical_alerts				OUT VARCHAR2,
		v_contrast_allergies			OUT VARCHAR2,
		v_special_needs					OUT VARCHAR2,
		v_specialty						OUT VARCHAR2,
		v_diagnosis						OUT VARCHAR2,
		v_admit_dttm					OUT VARCHAR2,
		v_register_dttm					OUT VARCHAR2,
		v_m_patient_id_issuer			OUT VARCHAR2,
		v_m_last_name					OUT VARCHAR2,
		v_m_first_name					OUT VARCHAR2,
		v_m_middle_name					OUT VARCHAR2,
		v_m_prefix						OUT VARCHAR2,
		v_m_suffix						OUT VARCHAR2,
		v_m_race_code					OUT VARCHAR2,
		v_m_account_no					OUT VARCHAR2,
		v_m_address						OUT VARCHAR2,
		v_m_order_entry_user_id			OUT VARCHAR2,
		v_m_order_entry_location		OUT VARCHAR2,
		v_m_order_callback_phone_no		OUT VARCHAR2,
		v_m_req_proc_status				OUT VARCHAR2,
		v_m_req_proc_code_scheme		OUT VARCHAR2,
		v_m_req_proc_code_version		OUT VARCHAR2,
		v_m_req_proc_code_meaning		OUT VARCHAR2,
		v_m_req_proc_location			OUT VARCHAR2,
		v_m_patient_arrange				OUT VARCHAR2,
		v_m_source_aetitle				OUT VARCHAR2,
		v_m_broker_aetitle				OUT VARCHAR2,
		v_m_broker_type					OUT VARCHAR2,
		v_m_study_ssn					OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE text_to_report
	(
		v_broker_aetitle				IN VARCHAR2,
		v_value01						IN VARCHAR2, 
		v_value02						IN VARCHAR2, 
		v_value03						IN VARCHAR2, 
		v_value04						IN VARCHAR2, 
		v_value05						IN VARCHAR2, 
		v_value06						IN VARCHAR2, 
		v_value07						IN VARCHAR2, 
		v_value08						IN VARCHAR2, 
		v_value09						IN VARCHAR2, 
		v_value10						IN VARCHAR2, 
		v_value11						IN VARCHAR2, 
		v_value12						IN VARCHAR2, 
		v_value13						IN VARCHAR2, 
		v_value14						IN VARCHAR2, 
		v_value15						IN VARCHAR2, 
		v_value16						IN VARCHAR2, 
		v_value17						IN VARCHAR2, 
		v_value18						IN VARCHAR2, 
		v_value19						IN VARCHAR2, 
		v_value20						IN VARCHAR2, 
		v_value21						IN VARCHAR2, 
		v_value22						IN VARCHAR2, 
		v_value23						IN VARCHAR2, 
		v_value24						IN VARCHAR2, 
		v_value25						IN VARCHAR2, 
		v_value26						IN VARCHAR2, 
		v_value27						IN VARCHAR2, 
		v_value28						IN VARCHAR2, 
		v_value29						IN VARCHAR2, 
		v_value30						IN VARCHAR2, 
		v_value31						IN VARCHAR2, 
		v_value32						IN VARCHAR2, 
		v_value33						IN VARCHAR2, 
		v_value34						IN VARCHAR2, 
		v_value35						IN VARCHAR2, 
		v_value36						IN VARCHAR2, 
		v_value37						IN VARCHAR2, 
		v_value38						IN VARCHAR2, 
		v_value39						IN VARCHAR2, 
		v_value40						IN VARCHAR2, 

		v_patient_id					OUT VARCHAR2,
		v_exam_id						OUT VARCHAR2,
		v_study_instance_uid			OUT VARCHAR2,
		v_report_stat					OUT VARCHAR2,
		v_creator_id					OUT VARCHAR2,
		v_creator_name					OUT VARCHAR2,
		v_create_dttm					OUT VARCHAR2,
		v_dictator_id					OUT VARCHAR2,
		v_dictator_name					OUT VARCHAR2,
		v_dictate_dttm					OUT VARCHAR2,
		v_transcriber_id				OUT VARCHAR2,
		v_transcriber_name				OUT VARCHAR2,
		v_transcribe_dttm				OUT VARCHAR2,
		v_approver_id					OUT VARCHAR2,
		v_approver_name					OUT VARCHAR2,
		v_approve_dttm					OUT VARCHAR2,
		v_reviser_id					OUT VARCHAR2,
		v_reviser_name					OUT VARCHAR2,
		v_revise_dttm					OUT VARCHAR2,
		v_report_type					OUT VARCHAR2,
		v_report_text					OUT LONG,
		v_conclusion					OUT LONG,
		v_study_dttm					OUT VARCHAR2,
		v_scheduled_location			OUT VARCHAR2,
		v_perform_department			OUT VARCHAR2,
		v_perform_modality				OUT VARCHAR2,
		v_request_dttm					OUT VARCHAR2,
		v_request_name					OUT VARCHAR2,
		v_request_code					OUT VARCHAR2,
		v_request_doctor				OUT VARCHAR2,
		v_perform_doctor				OUT VARCHAR2,
		v_refer_doctor					OUT VARCHAR2,
		v_scheduled_dttm				OUT VARCHAR2,
		v_patient_name					OUT VARCHAR2,
		v_patient_sex					OUT VARCHAR2,
		v_patient_birth_dttm			OUT VARCHAR2,
		v_admission_id					OUT VARCHAR2,
		v_study_comments				OUT VARCHAR2,
		v_study_reason					OUT VARCHAR2,
		v_attend_doctor					OUT VARCHAR2,
		v_r_event_type					OUT	VARCHAR2,
		v_r_report_control_id			OUT	VARCHAR2,
		v_r_broker_type					OUT	VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE study_to_text
	(
		v_broker_aetitle				IN	VARCHAR2,
		v_study_key						IN	NUMBER,
		v_patient_id					IN	VARCHAR2,
		v_exam_id						IN	VARCHAR2,
		v_study_stat					IN	VARCHAR2,
		v_study_instance_uid			IN	VARCHAR2,
		v_study_dttm					IN	VARCHAR2,
		v_request_code					IN	VARCHAR2,
		v_request_name					IN	VARCHAR2,
		v_perform_modality				IN	VARCHAR2,
		v_perform_department			IN	VARCHAR2,
		v_perform_station				IN	VARCHAR2,
		v_source_aetitle				IN	VARCHAR2,
		v_scheduled_location			IN	VARCHAR2,
		v_scheduled_dttm				IN	VARCHAR2,
		v_patient_location				IN	VARCHAR2,
		v_request_dttm					IN	VARCHAR2,
		v_study_desc					IN	VARCHAR2,
		v_bodyparts						IN	VARCHAR2,

		v_value01						OUT VARCHAR2,
		v_value02						OUT VARCHAR2,
		v_value03						OUT VARCHAR2,
		v_value04						OUT VARCHAR2,
		v_value05						OUT VARCHAR2,
		v_value06						OUT VARCHAR2,
		v_value07						OUT VARCHAR2,
		v_value08						OUT VARCHAR2,
		v_value09						OUT VARCHAR2,
		v_value10						OUT VARCHAR2,
		v_value11						OUT VARCHAR2,
		v_value12						OUT VARCHAR2,
		v_value13						OUT VARCHAR2,
		v_value14						OUT VARCHAR2,
		v_value15						OUT VARCHAR2,
		v_value16						OUT VARCHAR2,
		v_value17						OUT VARCHAR2,
		v_value18						OUT VARCHAR2,
		v_value19						OUT VARCHAR2,
		v_value20						OUT VARCHAR2,
		v_value21						OUT VARCHAR2,
		v_value22						OUT VARCHAR2,
		v_value23						OUT VARCHAR2,
		v_value24						OUT VARCHAR2,
		v_value25						OUT VARCHAR2,
		v_value26						OUT VARCHAR2,
		v_value27						OUT VARCHAR2,
		v_value28						OUT VARCHAR2,
		v_value29						OUT VARCHAR2,
		v_value30						OUT VARCHAR2,
		v_value31						OUT VARCHAR2,
		v_value32						OUT VARCHAR2,
		v_value33						OUT VARCHAR2,
		v_value34						OUT VARCHAR2,
		v_value35						OUT VARCHAR2,
		v_value36						OUT VARCHAR2,
		v_value37						OUT VARCHAR2,
		v_value38						OUT VARCHAR2,
		v_value39						OUT VARCHAR2,
		v_value40						OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE report_to_text
	(
		v_broker_aetitle				IN	VARCHAR2,
 		v_report_key					IN  NUMBER,
		v_patient_id					IN  VARCHAR2,
		v_exam_id						IN  VARCHAR2,
		v_study_instance_uid			IN  VARCHAR2,
		v_report_stat					IN  VARCHAR2,
		v_creator_id					IN  VARCHAR2,
		v_creator_name					IN  VARCHAR2,
		v_create_dttm					IN  VARCHAR2,
		v_dictator_id					IN  VARCHAR2,		-- 10
		v_dictator_name					IN  VARCHAR2,
		v_dictate_dttm					IN  VARCHAR2,
		v_transcriber_id				IN  VARCHAR2,
		v_transcriber_name				IN  VARCHAR2,
		v_transcribe_dttm				IN  VARCHAR2,
		v_approver_id					IN  VARCHAR2,
		v_approver_name					IN  VARCHAR2,
		v_approve_dttm					IN  VARCHAR2,
		v_reviser_id					IN  VARCHAR2,
		v_reviser_name					IN  VARCHAR2,		-- 20
		v_revise_dttm					IN  VARCHAR2,
		v_report_type					IN  VARCHAR2,
		v_report_text					IN  LONG,
		v_conclusion					IN  LONG,
		v_study_dttm					IN  VARCHAR2,
		v_scheduled_location			IN  VARCHAR2,
		v_perform_department			IN  VARCHAR2,
		v_perform_modality				IN  VARCHAR2,
		v_request_dttm					IN  VARCHAR2,
		v_request_name					IN  VARCHAR2,		-- 30
		v_request_code					IN  VARCHAR2,
		v_request_doctor				IN  VARCHAR2,
		v_perform_doctor				IN  VARCHAR2,
		v_refer_doctor					IN  VARCHAR2,
		v_scheduled_dttm				IN  VARCHAR2,
		v_patient_name					IN  VARCHAR2,
		v_patient_sex					IN  VARCHAR2,
		v_patient_birth_dttm			IN  VARCHAR2,
		v_admission_id					IN  VARCHAR2,
		v_study_comments				IN  VARCHAR2,		-- 40
		v_study_reason					IN  VARCHAR2,
		v_attend_doctor					IN  VARCHAR2,
		v_patient_location				IN  VARCHAR2,
		v_scheduled_station				IN  VARCHAR2,
		v_fxcode           				IN  VARCHAR2,
		v_fxdesc						IN  VARCHAR2,
		v_dxcode                        IN  VARCHAR2,
		v_dxdesc                        IN  VARCHAR2,		-- 48

		v_value01						OUT VARCHAR2,
		v_value02						OUT VARCHAR2,
		v_value03						OUT VARCHAR2,
		v_value04						OUT VARCHAR2,
		v_value05						OUT VARCHAR2,
		v_value06						OUT VARCHAR2,
		v_value07						OUT VARCHAR2,
		v_value08						OUT VARCHAR2,
		v_value09						OUT VARCHAR2,
		v_value10						OUT VARCHAR2,
		v_value11						OUT VARCHAR2,
		v_value12						OUT VARCHAR2,
		v_value13						OUT VARCHAR2,
		v_value14						OUT VARCHAR2,
		v_value15						OUT VARCHAR2,
		v_value16						OUT VARCHAR2,
		v_value17						OUT VARCHAR2,
		v_value18						OUT VARCHAR2,
		v_value19						OUT VARCHAR2,
		v_value20						OUT VARCHAR2,
		v_value21						OUT LONG,
		v_value22						OUT LONG,
		v_value23						OUT VARCHAR2,
		v_value24						OUT VARCHAR2,
		v_value25						OUT VARCHAR2,
		v_value26						OUT VARCHAR2,
		v_value27						OUT VARCHAR2,
		v_value28						OUT VARCHAR2,
		v_value29						OUT VARCHAR2,
		v_value30						OUT VARCHAR2,
		v_value31						OUT VARCHAR2,
		v_value32						OUT VARCHAR2,
		v_value33						OUT VARCHAR2,
		v_value34						OUT VARCHAR2,
		v_value35						OUT VARCHAR2,
		v_value36						OUT VARCHAR2,
		v_value37						OUT VARCHAR2,
		v_value38						OUT VARCHAR2,
		v_value39						OUT VARCHAR2,
		v_value40						OUT VARCHAR2
	);

	-------------------------------------------------------------------------------------------------
	PROCEDURE study_to_study
	(
		v_broker_aetitle				IN OUT	VARCHAR2,
		v_StudyKey						IN OUT  NUMBER,
		v_StudyInstanceUID				IN OUT	VARCHAR2,
		v_QueueStat						IN OUT	VARCHAR2,
		v_MatchStat						IN OUT	VARCHAR2,
		v_PatientId						IN OUT	VARCHAR2,
		v_ExamId						IN OUT	VARCHAR2,
		v_StudyStat       				IN OUT	VARCHAR2,
		v_StudyDttm						IN OUT	VARCHAR2,
		v_RequestCode					IN OUT	VARCHAR2,	-- 10
		v_RequestName					IN OUT	VARCHAR2,
		v_PerformModality               IN OUT	VARCHAR2,
		v_PerformDepartment 			IN OUT	VARCHAR2,
		v_PerformStation				IN OUT	VARCHAR2,
		v_SourceAETitle					IN OUT	VARCHAR2,
		v_ScheduledLocation				IN OUT	VARCHAR2,
		v_ScheduledDttm					IN OUT	VARCHAR2,
		v_PatientLocation				IN OUT	VARCHAR2,
		v_RequestDttm					IN OUT	VARCHAR2,
		v_StudyDesc						IN OUT	VARCHAR2,	-- 20
		v_Bodyparts						IN OUT	VARCHAR2,
		v_ScheduledProcStatus			IN OUT	VARCHAR2,
		v_ScheduledProcId				IN OUT	VARCHAR2,
		v_ScheduledProcDesc				IN OUT	VARCHAR2,
		v_PatientName					IN OUT	VARCHAR2,
		v_PatientSex					IN OUT	VARCHAR2,
		v_AdmissionId					IN OUT	VARCHAR2,
		v_SeriesCount					IN OUT  NUMBER,
		v_InstanceCount					IN OUT  NUMBER,		-- 29
		v_ObjectType					IN OUT  VARCHAR2,

		v_oru_field1					OUT	VARCHAR2,
		v_oru_field2					OUT	VARCHAR2,
		v_oru_field3					OUT	VARCHAR2,
		v_oru_field4					OUT	VARCHAR2,
		v_oru_field5					OUT	VARCHAR2,
		v_oru_field6					OUT	VARCHAR2,
		v_oru_field7					OUT	VARCHAR2,
		v_oru_field8					OUT	VARCHAR2,
		v_oru_field9					OUT	VARCHAR2,
		v_oru_field10					OUT	VARCHAR2
	);
	-------------------------------------------------------------------------------------------------
	PROCEDURE examresult_to_text
	(
		v_broker_aetitle					IN	VARCHAR2,
		v_hostname						IN VARCHAR2,
		v_trigger_dttm					IN VARCHAR2,
		v_patient_id						IN	VARCHAR2,
		v_patinet_name					IN VARCHAR2,
		v_study_dttm					IN	VARCHAR2,
		v_study_instance_uid		IN	VARCHAR2,
		v_accession_number			IN VARCHAR2,
		v_department_code			IN VARCHAR2,
		v_department_name			IN VARCHAR2,
		v_patient_location				IN VARCHAR2,
		v_study_desc					IN VARCHAR2,
		v_modality_code					IN VARCHAR2,
		v_object_type					IN VARCHAR2,
		v_message_type					IN VARCHAR2,

		v_value01						OUT VARCHAR2,
		v_value02						OUT VARCHAR2,
		v_value03						OUT VARCHAR2,
		v_value04						OUT VARCHAR2,
		v_value05						OUT VARCHAR2,
		v_value06						OUT VARCHAR2,
		v_value07						OUT VARCHAR2,
		v_value08						OUT VARCHAR2,
		v_value09						OUT VARCHAR2,
		v_value10						OUT VARCHAR2,
		v_value11						OUT VARCHAR2,
		v_value12						OUT VARCHAR2,
		v_value13						OUT VARCHAR2,
		v_value14						OUT VARCHAR2,
		v_value15						OUT VARCHAR2,
		v_value16						OUT VARCHAR2,
		v_value17						OUT VARCHAR2,
		v_value18						OUT VARCHAR2,
		v_value19						OUT VARCHAR2,
		v_value20						OUT VARCHAR2,
		v_value21						OUT VARCHAR2,
		v_value22						OUT VARCHAR2,
		v_value23						OUT VARCHAR2,
		v_value24						OUT VARCHAR2,
		v_value25						OUT VARCHAR2,
		v_value26						OUT VARCHAR2,
		v_value27						OUT VARCHAR2,
		v_value28						OUT VARCHAR2,
		v_value29						OUT VARCHAR2,
		v_value30						OUT VARCHAR2,
		v_value31						OUT VARCHAR2,
		v_value32						OUT VARCHAR2,
		v_value33						OUT VARCHAR2,
		v_value34						OUT VARCHAR2,
		v_value35						OUT VARCHAR2,
		v_value36						OUT VARCHAR2,
		v_value37						OUT VARCHAR2,
		v_value38						OUT VARCHAR2,
		v_value39						OUT VARCHAR2,
		v_value40						OUT VARCHAR2
	);
	-------------------------------------------------------------------------------------------------
	FUNCTION version
	RETURN VARCHAR2;
		PRAGMA RESTRICT_REFERENCES(version, WNDS, WNPS);

	-------------------------------------------------------------------------------------------------

END;
 /
SHOW ERRORS